default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_API_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY_BASE64"],
      is_key_content_base64: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        app_identifier: "com.pickflow"
      ) + 1,
      xcodeproj: "Pickflow.xcodeproj"
    )

    key_path = File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV["ASC_API_KEY_ID"]}.p8")

    gym(
      workspace: "Pickflow.xcworkspace",
      scheme: "Pickflow",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.pickflow" => ENV["PROVISIONING_PROFILE_SPECIFIER"]
        }
      },
      output_directory: "build",
      output_name: "Pickflow.ipa",
      xcargs: "-authenticationKeyPath #{key_path} -authenticationKeyID #{ENV["ASC_API_KEY_ID"]} -authenticationKeyIssuerID #{ENV["ASC_ISSUER_ID"]}"
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      changelog: ENV["RELEASE_NOTES"].to_s.empty? ? nil : ENV["RELEASE_NOTES"]
    )
  end
end
